#!/usr/bin/env bash

if [ -e "codingschoolschool" ]; then
   echo "codingschoolschool file exists"
   if [ -s "codingschoolschool" ]; then
       echo "codingschoolschool file is not empty"
   else
       echo "codingschoolschool file is empty"
   fi
   if [ -f "codingschoolschool" ]; then
       echo "codingschoolschool is a regular file"
   fi
else
   echo "codingschoolschool file does not exist"
fi
